![imagem%20unesp%20rosana.jpg](attachment:imagem%20unesp%20rosana.jpg)
# DataFrames

DataFrame é o elemeto mais importante dos Pandas e são diretamente inspirados pela linguagem de programação R. Podemos pensar em um DataFrame como um monte de objetos da série juntos para compartilhar o mesmo índice. Vamos usar Pandas para explorar esse tópico!

In [1]:
import pandas as pd
import numpy as np


In [2]:
from numpy.random import randn

In [16]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [17]:
df

W         X         Y         Z
A  0.686319  0.229970  0.609293 -0.065861
B  0.981586  0.607568  0.728827 -1.950053
C  0.011938  1.460471  1.132482  1.240234
D  0.427329 -0.768985 -1.533261  1.102118
E -0.310894  0.425854  1.048863 -0.705279

## Seleção e indexação

Vamos aprender os vários métodos para pegar dados de um DataFrame

In [5]:
df['W']

A   -0.228185
B    0.586498
C   -3.270696
D   -0.221027
E    1.775913
Name: W, dtype: float64

In [8]:
# Passando uma lista com nomes das colunas
df[['W','Z']]

W         Z
A -0.228185 -1.717268
B  0.586498 -0.506644
C -3.270696 -1.802588
D -0.221027 -0.586914
E  1.775913  2.248226

In [15]:
# Sintaxe SQL (Não recomendado!)
df

X         Y         Z
A  0.176259  1.554469 -1.717268
B  0.350517 -1.005000 -0.506644
C  0.507668  0.300174 -1.802588
D  0.178081 -0.263213 -0.586914
E  1.493787  0.383500  2.248226

As colunas dos DataFrames são Series

In [10]:
type(df['W'])

pandas.core.series.Series

** Criando uma coluna: **

In [18]:
df['joao'] = df['W'] + df['Y']

In [19]:
df

W         X         Y         Z      joao
A  0.686319  0.229970  0.609293 -0.065861  1.295612
B  0.981586  0.607568  0.728827 -1.950053  1.710413
C  0.011938  1.460471  1.132482  1.240234  1.144420
D  0.427329 -0.768985 -1.533261  1.102118 -1.105933
E -0.310894  0.425854  1.048863 -0.705279  0.737968

** Removendo colunas **

In [22]:
df.drop('joao',axis=1,inplace=True)

In [23]:
# Porém, tal exclusão só ocorrerá se especificada no parâmetro inplace
df

W         X         Y         Z
A  0.686319  0.229970  0.609293 -0.065861
B  0.981586  0.607568  0.728827 -1.950053
C  0.011938  1.460471  1.132482  1.240234
D  0.427329 -0.768985 -1.533261  1.102118
E -0.310894  0.425854  1.048863 -0.705279

In [22]:
df.drop('new',axis=1,inplace=True)

In [28]:
df

W         X         Y         Z
A  0.686319  0.229970  0.609293 -0.065861
B  0.981586  0.607568  0.728827 -1.950053
C  0.011938  1.460471  1.132482  1.240234
D  0.427329 -0.768985 -1.533261  1.102118
E -0.310894  0.425854  1.048863 -0.705279

Também podemos deletar colunas desta forma:

In [25]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

** Selecionando linhas: **

In [26]:
df.loc['D']

W    0.427329
X   -0.768985
Y   -1.533261
Z    1.102118
Name: D, dtype: float64

Ou selecione com base na posição em vez do rótulo

In [27]:
df.iloc[2]

W    0.011938
X    1.460471
Y    1.132482
Z    1.240234
Name: C, dtype: float64

In [26]:
df.iloc[0:4][2:3]

W         X         Y         Z       new
C -2.018168  0.740122  0.528813 -0.589001 -1.489355

** Selecionando o subconjunto de linhas e colunas **

In [29]:
df.loc['B','Y']

0.7288267384544105

In [29]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Seleção condicional

Uma característica importante dos pandas é a seleção condicional usando notação de colchetes, muito semelhante ao numpy:

In [30]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [41]:
A = np.arange(0,20)
b=A.reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
b>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [33]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [28]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

Para duas condições, você pode usar | e & com parênteses:

In [43]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
C  0.011938  1.460471  1.132482  1.240234

## Mais Detalhes do Índice

Vamos discutir mais alguns recursos de indexação, incluindo resetar o índice ou configurá-lo de outra forma. Também falaremos sobre hierarquia de índice!

In [44]:
df

W         X         Y         Z
A  0.686319  0.229970  0.609293 -0.065861
B  0.981586  0.607568  0.728827 -1.950053
C  0.011938  1.460471  1.132482  1.240234
D  0.427329 -0.768985 -1.533261  1.102118
E -0.310894  0.425854  1.048863 -0.705279

In [45]:
# Redefinir para o padrão 0,1 ... n índice
df.reset_index()

index         W         X         Y         Z
0     A  0.686319  0.229970  0.609293 -0.065861
1     B  0.981586  0.607568  0.728827 -1.950053
2     C  0.011938  1.460471  1.132482  1.240234
3     D  0.427329 -0.768985 -1.533261  1.102118
4     E -0.310894  0.425854  1.048863 -0.705279

In [38]:
novoind = 'CA NY WY OR CO'.split()

In [39]:
df['Estados'] = novoind

In [40]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [41]:
df.set_index('Estados')

W         X         Y         Z
Estados                                        
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

In [42]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [43]:
df.set_index('Estados',inplace=True)

In [44]:
df

W         X         Y         Z
Estados                                        
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

## Hierarquia de índices e índices múltiplos

Vamos examinar como trabalhar com o Multi-Index, primeiro criaremos um exemplo rápido de como seria um DataFrame Multi-Indexado:

In [45]:
# Níveis de Índice
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [29]:
zip??

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(iter1 [,iter2 [...]]) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type


In [40]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [47]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -0.497104 -0.754070
   2 -0.943406  0.484752
   3 -0.116773  1.901755
G2 1  0.238127  1.996652
   2 -0.993263  0.196800
   3 -1.136645  0.000366

Agora vamos mostrar como indexar isso! Para a hierarquia de índice, usamos df.loc []. Se este fosse no eixo das colunas, você usaria a notação de suporte normal df []. Chamar um nível do índice retorna um sub-dataframe:

In [49]:
df.loc['G1']

A         B
1 -0.497104 -0.754070
2 -0.943406  0.484752
3 -0.116773  1.901755

In [48]:
df.loc['G1'].loc[1]

A   -0.497104
B   -0.754070
Name: 1, dtype: float64

In [44]:
df.index.names

FrozenList([None, None])

In [45]:
df.index.names = ['Grupo','Número']

In [46]:
df

A         B
Grupo Número                    
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [47]:
df.xs('G1')

A         B
Número                    
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [48]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [49]:
df.xs(1,level='Número')

A         B
Grupo                    
G1     0.302665  1.693723
G2     0.166905  0.184502